remote_theme: just-the-docs/just-the-docs
markdown: GFM

title: ajrp-tec

background: dark
color_scheme: dark

# Enable or disable heading anchors
# heading_anchors: false
# Add custom styles for a dark theme


# Resten af dine konfigurationsindstillinger for navigation
#nav_external_links:
#  - title: Temaer
#    url: https://ajrptec.github.io
#    hide_icon: true
#  # ... (de øvrige links)
